# Generated by Django 5.0 on 2024-01-07 23:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="person",
            old_name="name",
            new_name="person_name",
        ),
    ]
